"""Preprocessing script to generate dataset with only handcrafted features
related to eviction.
"""

import pandas as pd


EVICT = {
    'f4i23e': 'In past 12 months, evicted from home or apt for not paying the rent or mortgage?',
    'm4i23e': 'In past 12 months, evicted from home or apt for not paying the rent or mortgage?',
    'm3i23c': 'In past year, were you evicted from home?',
    'f3i23c': 'In past year, were you evicted from home?',
    'm5f23d': 'F23D. Were evicted from home/apartment for not paying rent in past 12 months',
    'm2h19e': 'In past 12 months, did you-Get evicted for not paying rent/mortgage?',
    'f2h17e': 'In past 12 months, did you-Get evicted for not paying rent/mortgage?',
    'n5g1d': 'G1D. Evicted from home or apartment for not paying rent or mortgage',
    'f5f23d': 'F23D. Were evicted from home/apartment for not paying rent in past 12 months'
}

RENT = {
    'f4i23d': 'In past 12 months, did not pay full amt rent/mortgage payments b/c wasn\'t enough',
    'f4i23e': 'In past 12 months, evicted from home or apt for not paying the rent or mortgage?',
    'm2h4': 'How much rent do you pay each month?',
    'm2h7': 'Is fed, state, or local gov helping to pay your rent?',
    'm4i23e': 'In past 12 months, evicted from home or apt for not paying the rent or mortgage?',
    'f3i5a': 'INT CHK: DOES R LIVE WITH FAMILY OR FRIENDS, BUT PAY NO RENT?',
    'm3i23b': 'In past year, did you not pay full rent or mortgage?',
    'f3i23b': 'In past year, did you not pay full rent or mortgage ?',
    'f1f4': 'Is the fed/state/local government helping you to pay your rent?',
    'f4i4': 'How much rent do you pay each month?',
    'f4i6': 'Is the federal, state, or local government helping to pay for your rent?',
    'f4i5a': 'INT CHK: DOES RESPONDENT LIVE WITH FAMILY OR FRIENDS BUT PAY NO RENT?',
    'm4i5a': 'INT CHK: DOES RESPONDENT LIVE WITH FAMILY OR FRIENDS BUT PAY NO RENT?',
    'f3i6': 'Is the federal/state/local government helping you pay your rent?',
    'f3i4': 'How much rent do you pay each month? ($)',
    'f1f2': 'Is the home/apt of your current residency owned or rented?',
    'f2h6': 'Is fed, state, or local gov helping to pay rent?',
    'm5f23c': 'F23C. Did not pay full amount of rent/mortgage payments in past 12 months',
    'm5f23d': 'F23D. Were evicted from home/apartment for not paying rent in past 12 months',
    'm2h19e': 'In past 12 months, did you-Get evicted for not paying rent/mortgage?',
    'm2h6': 'Int Chk: Does respondent live w/family/friends, but pay no rent?',
    'f2h17d': 'In past 12 months, did you-Not pay full amount of rent/mortgage?',
    'f2h17e': 'In past 12 months, did you-Get evicted for not paying rent/mortgage?',
    'm4i4': 'How much rent do you pay each month?',
    'm4i6': 'Is the federal, state, or local government helping to pay for your rent?',
    'f5f4': 'Amount of rent paid each month',
    'm4i23d': 'In past 12 months, did not pay full amt rent/mortgage payments b/c wasn\'t enough',
    'm1f4': 'Is the fed/state/local government helping to pay for your rent?',
    'n5g1c': 'G1C. Rent or mortgage was not paid because not enough money',
    'n5g1d': 'G1D. Evicted from home or apartment for not paying rent or mortgage',
    'f2h4': 'How much rent is payed each month?',
    'm3i5a': 'Does respondent live with family/friends, but pays no rent?',
    'f2h5a': 'Int Chk: Does respondent live with family or friends, but pay no rent?',
    'm5f4': 'F4. Amount of rent paid each month',
    'm5f6': 'F6. The federal, state, or local government helps to pay for your rent',
    'm3i6': 'Is the federal/state/local government helping you pay your rent?',
    'm2h19d': 'In past 12 months, did you-Not pay full amount of rent/mortgage?',
    'f1k4': 'What are your mo expenses for rent or mortgage?',
    'm3i4': 'How much rent do you pay each month?',
    'f5f23c': 'F23C. Did not pay full amount of rent/mortgage payments in past 12 months',
    'f5f23d': 'F23D. Were evicted from home/apartment for not paying rent in past 12 months',
    'f5f6': 'F6. The federal, state, or local government helps to pay for your rent'
}

MONEY = {
    'm3k27a': 'In past year, did you do anything else to earn money?',
    'm3d9g': 'In last month of rel: did father withhold/make you ask/take money?',
    'k5f1c': 'F1C. Taken money at home',
    'm1b4a': 'Why did rom rel end with (BF), Financial Reasons(Don\'t have work,money)?',
    'm3b16a4': 'How much money does [employer] give you? ($)',
    'f3b16a4': 'How much money does [employer] give you? ($)',
    'f3b16a5': 'How much money does [child care center] give you? ($)',
    'f3b16a6': 'How much money does [head start] give you? ($)',
    'f3b16a7': 'How much money do [other] give you? ($)',
    'f3b16a1': 'How much money does [child\'s mother] give you? ($)',
    'f3b16a2': 'How much money do [relative] give you? ($)',
    'f3b16a3': 'How much money does [gov agency] give you? ($)',
    'f4i23h': 'In past 12 months, borrow money from friends or family to help pay bills?',
    'f4i23l': 'In past 12 months, cut back buying clothes for yourself b/c wasn\'t enough money?',
    'f4i23n': 'In past 12 months, phone service disconnected b/c wasn\'t enough money?',
    'f4i23a': 'In past 12 months, receive free food or meals because there wasn\'t enough money?',
    'f4i23g': 'In past 12 months, electricity turned off by utility co b/c wasn\'t enough money?',
    'f1b6a': 'When last tgthr, how often did you disagree about money?',
    'f3c38a': 'What is the range of money of the arrears?',
    'f5f23k': 'F23K. Telephone service disconnected because wasn\'t enough money in past 12 mont',
    'f5e2b': 'E2B. Amount of financial help or money father was given in past 12 months',
    'm4k26e': 'How much money did you receive in the last 12 months for this activity?',
    'm2h9c3': 'How much money did you receive last month from other assistance?',
    'm2h9c2': 'How much money did you receive last month from food stamps?',
    'm2h9c1': 'How much money did you receive last month from welfare/TANF?',
    'm5i26e1': 'I26E1. Range received in last 12 months for doing something else to earn money',
    'f5j2a': 'J2A. Amount you gave/loaned money to friends/relatives during past 12 months',
    'm5i26a': 'I26A. You did something else to earn money during past 12 months',
    'm3b16a2': 'How much money does [relative] give you? ($)',
    'm4k24e': 'How much money did you receive in the last 12 months for your own business?',
    'm4c20c': 'Not includ formal child support, how much money did you receive from father?',
    'm4k25e': 'How much money did you receive in the last 12 months for this activity?',
    'm2b29': 'Does any person/agency provide money/voucher/scholarship for child care?',
    'm4l2': 'In past 12 months have you given/loaned any money to friends or relatives?',
    'f5b16b': 'B16B. Given other money directly to mother instead of paying child support',
    'f5b16c': 'B16C. Amount of money you gave to mother, not including formal child support',
    'f5b16d': 'B16D. Range of amount of money you gave to mother, not including child support',
    'f3l2a': 'In past year, how much money did you give/loan?',
    'f1b21a': 'About how much money/month did you say you would provide?',
    'm1b23a': 'In last mo, how often did you and BF disagree on money?',
    'm2k20b': 'In past 12 mths, how many weeks did you earn money other ways?',
    'm2k20c': 'In past 12 mths, how many hrs per wk did you do other things to earn money?',
    'm2k20d': 'When earning money other ways, did you receive cash, or something else?',
    'm2k20e': 'How much did you receive past 12 mths doing something else to earn money?',
    'm2k20f': 'Was other type of payment received for doing something else for money?',
    'm2b31e': 'How much money does child care center give you? ($)',
    'm2b31g': 'How much money does other person/agency give you? ($)',
    'm2b31f': 'How much money does head start/early head start give you? ($)',
    'f5e2c': 'E2C. Range of amount of financial help/money father was given in past 12 mos.',
    'f5i26b': 'I26B. Number of weeks you did something else to earn money during last 12 months',
    'f5i26c': 'I26C. Number of hrs/week during those weeks you did something else to earn money',
    'f5i26a': 'I26A. You did something else to earn money during past 12 months',
    'f5i26e': 'I26E. Amount received in last 12 months for doing something else to earn money',
    'm4i23a': 'In past 12 months, receive free food or meals because there wasn\'t enough money?',
    'm3k27d': 'When earning money other ways, did you receive cash/something else?',
    'm4k26c': 'During those weeks how many hrs/wk did you do anything else to earn money?',
    'm3c36c': 'Could you give me a range of money father pays each month?',
    'm4i23g': 'In past 12 months, electricity turned off by utility co b/c wasn\'t enough money?',
    'm5c6g': 'C6G. He withholds money, makes you ask for money, or takes your money',
    'p5j7b': 'J7B. Range of money spent on groceries',
    'm4i23h': 'In past 12 months, borrow money from friends or family to help pay bills?',
    'm4c20b': 'Has father given money/financial support instead/in add to formal child support?',
    'f3d7g': 'Often/sometimes/never: she withholds money, makes you ask, takes it?',
    'm3l5d': 'Who in household controls money?',
    'f2d5g': 'How often does mother-withhold/ try to control your money?',
    'm4h2b': 'About how much financial help or money were you given in the past twelve months?',
    'm4h2c': 'How much financ help/money were you given in past 12 months - range?',
    'f1b23a': 'In last mo, how often did you disagree about money?',
    'm1b12a': 'In last mo, how often did you and BF disagree about money?',
    'm2g5a4': 'Who gave you financial help/money?-Other paternal relatives',
    'm2g5a6': 'Who gave you financial help/money?-Boyfriend/partner',
    'm2g5a7': 'Who gave you financial help/money?-Partner\'s Family',
    'm2g5a2': 'Who gave you financial help/money?-Other maternal relatives',
    'm2g5a8': 'Who gave you financial help/money?-Other',
    'k5a1e': 'A1E. How often PCG knows what you spend money on',
    'f3d9g': 'In last month of rel: mom withhold/make you ask for/take money?',
    'f2g7a2': 'Who gave you financial help/money?-Other paternal relatives',
    'f2g7a1': 'Who gave you financial help/money?-respondents\' Parents',
    'f2g7a8': 'Who gave you financial help/money?-Other',
    'f3c29b': 'What is the approximate range in money you have given?',
    'm5j5d': 'J5D. Who controls the money in this household',
    'm5j5b': 'J5B. Way money is handled as a couple',
    'f5b22_103': 'B22_103. Allowance or spending money',
    'f5e2a_7': 'E2A_7. Girlfriend/partner gave financial help or money',
    'm2g5a5': 'Who gave you financial help/money?-Friends',
    'm2g5a3': 'Who gave you financial help/money?-Father\'s Parents',
    'f5e2a_3': 'E2A_3. Mother gave financial help or money',
    'f3j0b2': 'How important is money for your happiness?',
    'f5e2a_5': 'E2A_5. Other relatives of mother gave financial help or money',
    'p5j10b': 'J10B. Range of money spent on eating out in last month',
    'f4l2': 'In past year, have you given/loaned any money to friends or relatives?',
    'f5e2a_6': 'E2A_6. Friend(s) gave financial help or money',
    'm4d9g': 'How often did father withhold money, make you ask for money, or take your money?',
    'm2l2': 'In past 12 mths, have you given any money to friends/relatives?',
    'f4d7g': 'Often/sometimes/never: withhold money, make you ask, takes money?',
    'f4k25e1': 'How much money did you receive in the last 12 months for this activity (range)?',
    'f2b27e': 'How much money does child care center give you? ($)',
    'f2b27b': 'How much money do relatives not living with you give you? ($)',
    'f2b27a': 'How much money does child\'s mother (not live-in) give you? ($)',
    'f3b14': 'Does any person/agency give you money/scholarship for care?',
    'f3c26a': 'Could you give me a range of money you have given?',
    'f4e8': 'Does CP engage in activities (other than reg job) for money, meals, etc?',
    'f3k25e1': 'How much money did you receive in past 12 months from business? ($)',
    'f1b24d': 'How life diff if NOT married BM, Control over money?',
    'f5b22x': 'B22X. Frequency mother gives you money or buys things directly for child',
    'm3c20a': 'Could you give me a range of money paid by father?',
    'm3b16a3': 'How much money does [gov agency] give you? ($)',
    'm3b16a1': 'How much money does [child\'s father] give you? ($)',
    'm3b16a7': 'How much money does [other] give you? ($)',
    'm3b16a6': 'How much money does [head start] give you? ($)',
    'm3b16a5': 'How much money does [child care center] give you? ($)',
    'f1k2a': 'How much money did you receive from Public assis./Welfare etc.?',
    'f1k2c': 'How much money did you receive from Family/Friends?',
    'f1k2b': 'How much money did you receive from Unemployment/SS/Disability?',
    'm5e2': 'E2. Financial help or money from anyone other than father',
    'm1b15d': 'How life diff if married BF, control over money?',
    'm2k20a1': 'What else did you do to earn money?',
    'm3i23e': 'In past year, did you borrow money from friends/family?',
    'p5j10': 'J10. Amount of money spent eating out in last month',
    'f5e2a_91': 'E2A_91. Other (specify) gave financial help or money',
    'f3i23e': 'In past year, did you borrow money from friends/family?',
    'f3e8': 'Does CP engage in activities other than regular job for money or necessities?',
    'm1j4': 'At the end of the month how much money leftover do you usually have?',
    'm3b14': 'Does any person/agency give you money/scholarship to help pay for care?',
    'f4b13': 'Does person/agency give money/voucher/scholars to help pay for care?',
    'm5j2a': 'J2A. Amount you gave/loaned money to friends/relatives during past 12 months',
    'f5j2': 'J2. You gave/loaned money to friends/relatives in past 12 months',
    'm2l2a': 'In past 12 mons, how much money did you give to friends/relatives?',
    'm3e23g': 'Often/sometimes/never: CP withholds/make you ask/takes money?',
    'm3c25': 'How often does father give you this money when he is supposed to?',
    'f4c20c': 'How much money have you given mother  last 2 yrs, not formal child support?',
    'm4l5b': 'How do you handle your money?',
    'm4c20d': 'Not includ formal child support, how much money you receive from father? (range)',
    'f2k25a1': 'What else did you do to earn money?',
    'k5e2c': 'E2C. Frequency kids take your things, like your money or lunch',
    'm2d6g': 'How often does father-Withhold/ try to control your money?',
    'n5a17b': 'A17B. BioM and/or BioF give you regular amount of money each month',
    'f4d9g': 'Often/sometimes/never: withhold money, make you ask, takes money?',
    'm3k27c': 'In past year, how many hrs/week did you do activity to earn money?',
    'm4d7g': 'How often father withhold money, make you ask for money, or take your money?',
    'm1b6a': 'When you and BF tgthr how often did you disagree about money?',
    'm5e2b': 'E2B. Amount of financial help or money mother was given in past 12 months',
    'm5e2c': 'E2C. Range of amount of financial help/money mother was given in past 12 mos.',
    'm4k24e1': 'How much money did you receive in last 12 months for your own business (range)?',
    'm3e8': 'Does CP do activities other than regular job for money or necessities?',
    'm2l8': 'How do you and husband/partner keep money - separate or together?',
    'm2d8g': 'During last mth of rel did father-Withhold/ try to control your money?',
    'f5e2a_4': 'E2A_4. Mother\'s parents gave financial help or money',
    'm5i26c': 'I26C. Number of hrs/week during those weeks you did something else to earn money',
    'f2c15a': 'How often do you give this money when you\'re supposed to?',
    'm3c20b': '18C ONLY: Has father given money/support (instead of/in addition) child support?',
    'f4c20d': 'How much money given mother  last 2 yrs, not formal chld supp, range?',
    'm1b24d': 'How life diff if NOT married BF, control over money?',
    'm4b13': 'Does person/agency give money, voucher, scholarship to help pay for childcare?',
    'm2g5a1': 'Who gave you financial help/money?-respondent\'s Parents',
    'm3l2': 'In past year, have you given/loaned money to friends/relatives?',
    'p5j9b': 'J9B. Range of money spent on take out food or delivery',
    'f4k26c': 'During those weeks how many hrs/wk did you do anything else to earn money?',
    'f4k26e': 'How much money did you receive in the last 12 months for this activity?',
    'f5j9f': 'J9F. Any other loans or money you owe to a bank/lending institution',
    'f5a4k_1': 'A4K_1. Financial reasons (don\'t have work/money)',
    'm2c20a': 'How often does father give you money when he\'s supposed to?',
    'm4i23l': 'In past 12 months, cut back buying clothes for yourself b/c wasn\'t enough money?',
    'm5f23g': 'F23G. Borrowed money from friends/family to help pay bills in past 12 months',
    'm5f23f': 'F23F. Gas/electric service turned off because not enough money in past 12 months',
    'm2e8g': 'How often does partner-Withhold/ try to control your money?',
    'f4k25e': 'How much money did you receive in the last 12 months for this activity?',
    'm1j2b': 'In 12 mo, about how much money did you receive from pub. assis/welfare?',
    'm5j9f': 'J9F. Any other loans or money you owe to a bank/lending institution',
    'm3d7g': 'Often/sometimes/never: he withholds money, makes you ask for it, takes it?',
    'f4k24e': 'How much money did you receive in the last 12 months for your own business?',
    'f5e2a_8': 'E2A_8. Partner\'s family gave financial help or money',
    'f5e2a_2': 'E2A_2. Other relatives of father gave financial help or money',
    'f3k27d': 'When earning money other ways, did you receive cash/something else?',
    'f3k27a': 'In past year, did you do anything else to earn money?',
    'f3k27c': 'In past year, how many hours/week did you do other things to earn money?',
    'f3k27b': 'In past year, how many weeks did you earn money doing other things?',
    'p5i27': 'I27. Frequency you know how child spends money',
    'f2g7a3': 'Who gave you financial help/money?-mother\'s parents',
    'f2g7a7': 'Who gave you financial help/money?-Partner\'s family',
    'f2g7a6': 'Who gave you financial help/money?-Girlfriend/partner',
    'f2g7a5': 'Who gave you financial help/money?-Friends',
    'f2g7a4': 'Who gave you financial help/money?-Other maternal relatives',
    'f2fc12': 'Who does the money go to?',
    'f3l2': 'In past year, given/loaned money to friends/relatives?',
    'f2b27g': 'How much money does other give you? ($)',
    'f2b27f': 'How much money does head/early head start give you? ($)',
    'f2b27d': 'How much money does employer give you? ($)',
    'f2b27c': 'How much money does government agency give you? ($)',
    'm5b16b': 'B16B. Father has given money directly instead of formal child support in past ye',
    'f5i26e1': 'I26E1. Range received in last 12 months for doing something else to earn money',
    'm2b31b': 'How much money does your relative (not living with you) give you? ($)',
    'm1b21a': 'How much money per mo did BF say he would provide?',
    'f3c20a': 'Could you give me a range of money you paid?',
    'f5j5d': 'J5D. Who controls the money in this household',
    'f5j5b': 'J5B. Way money is handled as a couple',
    'f3k25e': 'How much money did you receive in past 12 months from your business?',
    'm3l2a': 'In past year, how much money did you give/loan? ($)',
    'm4k26e1': 'How much money did you receive in the last 12 months for this activity (range)?',
    'm2k20a': 'In past 12 mths, did you-Do anything else to earn money?',
    'm2b31a': 'How much money does child\'s father (not live in) give you? ($)',
    'm2b31c': 'How much money does government agency give you? ($)',
    'f2l2': 'In past 12 mons, have you given any money to friends/relatives?',
    'f2l7': 'How do you and partner handle money?',
    'm2b31d': 'How much money does employer give you? ($)',
    'm4e23g': 'How often partner withhold money, make you ask for money, or take your money?',
    'm4i23n': 'In past 12 months, phone service disconnected b/c wasn\'t enough money?',
    'n5g1a': 'G1A. Received free food or meals in past twelve months because not enough money',
    'n5g1b': 'G1B. Was hungry but did not eat because not enough money',
    'n5g1c': 'G1C. Rent or mortgage was not paid because not enough money',
    'n5g1e': 'G1E. Gas, oil, or electricity bill was not paid because not enough money',
    'n5g1g': 'G1G. Borrowed money from friends or family to help pay bills',
    'm5i26b': 'I26B. Number of weeks you did something else to earn money during last 12 months',
    'f1b16': 'During BM preg, did you give her money or buy things for the baby/ies?',
    'm1b16': 'During preg did BF give money to buy things for baby/babies?',
    'mx1j2': 'In the last 12 months, about how much money did you receive from (J1)?',
    'm3j0b2': 'How important is money to your happiness?',
    'f4b8d': 'Does person/agency give money/voucher/scholarship to help pay for program,?',
    'm2c38a': 'How much money does father earn per year?-($ Range)',
    'm2c38': 'How much money does father normally earn per year?-($ Amount)',
    'm3k27b': 'In past year, how many weeks did you earn money doing other things?',
    'm5d20g': 'D20G. Current partner withholds money, makes you ask for money, or takes your mo',
    'f4k26a': 'During the past 12 months, did you do anything else to earn money?',
    'f4k26b': 'In last 12 months how many weeks did you do anything else to earn money?',
    'f1b12a': 'In last mo how often, disagree about money?',
    'm5i26e': 'I26E. Amount received in last 12 months for doing something else to earn money',
    'm4l2a': 'During past 12 months how much money did you give/loan to friends/relatives?',
    'f4k24e1': 'How much money did you receive in last 12 months for your own business (range)?',
    'm3l5b': 'How does couple handle money?',
    'f3l5d': 'Who in household controls money?',
    'f3l5b': 'How does couple handle money?',
    'f2k25b': 'In past 12 mons, how many weeks did you earn money doing other things?',
    'f2k25c': 'In past 12 mons, how many hrs per wk did you do other things to earn money?',
    'f2k25a': 'In past 12 mons, did you do anything else to earn money?',
    'f2k25d': 'When earning money other ways, did you receive cash, or something else?',
    'm4e8': 'Does part do anythg other than reg paid employ to make money/other necessities?',
    'm2k10ap': 'You earn this money over what time-span?',
    'm5j2': 'J2. You gave/loaned money to friends/relatives in past 12 months',
    'f4l5b': 'How do you handle your money?',
    'f4l5d': 'Who would you say controls the money in this household?',
    'm4b8d': 'Does person or agency give money, voucher, scholarship to help pay for program?',
    'm4k26a': 'During the past 12 months, did you do anything else to earn money?',
    'm4k26b': 'In last 12 months how many weeks did you do anything else to earn money?',
    'f3c25': 'How often do you give this money when you are supposed to?',
    'm5b22_103': 'B22_103. Allowance or spending money',
    'f2d7g': 'How oft during last mon/rel did mother-Withhold/ try to control your money?',
    'f4k26e1': 'How much money did you receive in the last 12 months for this activity (range)?',
    'f5c6g': 'C6G. She withholds money, makes you ask for money, or takes your money',
    'm1j2c': 'In last 12 mo, about how much money did you receive from unemployment/SS/disabil',
    'm1j2a': 'In last 12 mo, about how much money did you receive from earnings?',
    'm1j2d': 'In last 12 mo, about how much money did you receive from family/friends?',
    'm2h19i': 'In past 12 months, did you-Borrow money from family/friends to pay bills?',
    'f1b15d': 'How life diff if married BM, control over money?',
    'm4k25e1': 'How much money did you receive in the last 12 months for this activity (range)?',
    'f4l2a': 'During past year, how much money did you give/loan to friends/relatives?',
    'f1k5': 'At the end of the mo, how much money do you usually have?',
    'f3c35': 'Could you give me the range of money you pay each month?',
    'f2b25': 'Does any person/agency provide money/voucher/scholarship for child care?',
    'm5f23k': 'F23K. Telephone service disconnected because wasn\'t enough money in past 12 mont',
    'f5f23f': 'F23F. Gas/electric service turned off because not enough money in past 12 months',
    'f5f23g': 'F23G. Borrowed money from friends/family to help pay bills in past 12 months',
    'm4l5d': 'Who would you say controls the money in this household?',
    'f1b4a': 'Why did romantic rel end with BM, Financial Reasons(Don\'t have work,money)?',
    'f2l2a': 'During past 12 mons how much money all together did you give friends/family?',
    'f5e2a_1': 'E2A_1. Respondent\'s parents gave financial help or money'
}

JOB = {
    'f1j4': 'What would be the hourly wage in order for you to take a job?',
    'f1j6': 'How many hrs/wk do/did you work at your current/most recent job?',
    'f1j2': 'Are you currently looking for a regular job?',
    'f3c44': 'Does mother have problems with job/family/friends because of alcohol/drug use?',
    'm1i7': 'Does BF engage in any activities other than regular job to generate income?',
    'm1i9': 'Does BF have a problem keeping a job/friends because of drugs/alc use?',
    'f3k2_8': 'What program/school attending: job corps?',
    'f2k5a14': 'What program/schooling have you completed?-Program to help get job',
    'f2k5a13': 'What program/schooling have you completed?-Job skills program',
    'f4i23m': 'In past 12 months, you worked overtime or taken a second job?',
    'm4k13p': 'How much you usual earn in job, before taxes and deductions? (per)',
    'm5g22k': 'G22K. Use of substances in past 12 mos. interfered with work at school/job/home',
    'm4k3a_14': 'What program/school completed: program to help get a job',
    'm2k6b': 'Why aren\'t you looking for a regular job?',
    'm1d2c': 'How imp for successful marriage, wife has steady job?',
    'f2k5a8': 'What program/schooling have you completed?-Job corps',
    'kind_f1d': '-->f1d. i enjoy my present teaching job',
    'm3e7a1': 'When did CP last have job lasting two consecutive weeks or more (month)?',
    'm3e7a2': 'When did CP last have paid job lasting two consecutive weeks or more (year)?',
    'm4e10': 'Partner have probs keeping job/getting along w/family/friends b/c alcohol/drug?',
    'f5i14a5': 'I14A5. At your primary job you regularly work different times each week',
    'f5i14a3': 'I14A3. At your primary job you regularly work nights',
    'f5g20': 'Drinking/hangover interfered with work at school/job/home during past 12 months',
    'f5g22': 'G22. Use of substances in past 12 mos. interfered with work at school/job/home',
    'm5i11': 'I11. You work for yourself or for someone else in this job',
    'm5i13': 'I13. Amount you usually earn in this job before taxes/deductions',
    'f4k17': 'Ever time in past year you worked more than 1 regular job at the same time?',
    'f4e7a2': 'When did CP last work at job last 2 weeks+ for reg paycheck? (year)',
    'f4e7a1': 'When did CP last work at job last 2 weeks+ for reg paycheck? (month)',
    'f4k3a_13': 'What program/school completed: learn job skills',
    'f4j23': 'In past year, did your use of substances interfere w/work at school/job/home?',
    'f4j21': 'In last yr, did drinking/hangover interfere with your work at school/job/home?',
    'f2k3m': 'What kind of school/program are you attending?-Job skills program',
    'f1d2b': 'How imp for successful marriage, husband has steady job?',
    'f1d2c': 'How imp for successful marriage, wife has steady job?',
    'm4c36': 'What father doing last week-working a reg job, school, or something else?',
    'm4k2_8': 'What school/program attending: job corps',
    'm4k14a5': 'At your primary job, do you regularly work different times each week?',
    'f3k9b': 'When did you last work at job lasting two weeks or more? (year)',
    'f3k9a': 'When did you last work at job lasting two weeks or more? (month)',
    'm1i2i': 'In what mo did you last work 2 weeks or more at a regular job?',
    'f5f16a_2': 'F16A_2. Required to work in a paid job',
    'f5f16a_3': 'F16A_3. Required to work in an unpaid job',
    'f5f16a_1': 'F16A_1. Required to look for a job',
    'o5a7a': 'A7A. Peeling paint, needs paint job',
    'm2k6c': 'What would the hourly wage have to be for you to take a job?',
    'm2k6a': 'How long have you been looking for a regular job?',
    'm3c44': 'Does father have problems with job/family/friends because of alcohol/drug use?',
    'm3k23': 'Range of number of these jobs you had in past 3 years?',
    'f2h12a1': 'What were you required to do?-Look for a job',
    'm4i16a_3': 'What were you required to do: work in an unpaid job?',
    'm4i16a_2': 'What were you required to do: work in a paid job?',
    'm4i16a_1': 'What were you required to do: look for a job?',
    'f4i16a_1': 'What were you required to do: look for a job?',
    'f4k9b': 'When you last work reg job for 2 weeks+ to receive reg paycheck (year)?',
    'f4k9a': 'When you last work reg job for 2 weeks+ to receive reg paycheck (month)?',
    'm1i2ii': 'In what yr did you last work 2 weeks or more at a regular job?',
    'm5i14a5': 'I14A5. At your primary job you regularly work different times each week',
    'm1i6a1': 'In what mo did BF last work 2 weeks or more at a regular job?',
    'm3k9a': 'When did you last work at job lasting 2 weeks/more? (month)',
    'm2k7a': 'When did you last work at regular job lasting 2 consecutive weeks?-(Month)',
    'm2k7b': 'When did you last work at regular job lasting 2 consecutive weeks?-(Year)',
    'f3b23': 'Have you quit job/school because of child care problems?',
    'f3e10': 'Does CP have problems such as keeping job/friends due to alcohol/drugs?',
    'f2b30b': 'Since child\'s birth did you have to quit school/job due to lack of child care?',
    'm4j21': 'In last yr, did drinking/hangover interfer with your work at school/job/home?',
    'm4j23': 'In past 12 months, did your use of substances interfere w/work at school/job/hom',
    'm2k14': 'During past 12 mons, have you worked more than one regular job at a time?',
    'm3k9b': 'When did you last work at job lasting 2 weeks/more? (year)',
    'm3k2_8': 'What program/school: job corps?',
    'f5i3a_8': 'I3A_8. Completed job corps',
    'm4k9a': 'When you last work reg job for 2 weeks+ to receive reg paycheck (month)?',
    'm4k9b': 'When you last work reg job for 2 weeks+ to receive reg paycheck (year)?',
    'f4e8': 'Does CP engage in activities (other than reg job) for money, meals, etc?',
    'f5i6': 'I6. Length of time you have been looking for a regular job',
    'm5f7b': 'F7B. Received help from a welfare office or welfare job placement in past 12 mon',
    'm1i6a2': 'In what yr did BF last work 2 weeks or more at a regular job?',
    'f3e7a2': 'When did CP last have paid job lasting two consecutive weeks or more? (year)',
    'm2k3a13': 'What program/schooling have you completed?-Job skill program',
    'f4c39': 'Does mother have problems keeping job/getting along with friends because alc/dru',
    'm2k6': 'Are you currently looking for a regular job?',
    'f3k19': 'When you were working more than 1 job, how many hours did you work?',
    'f3i23j': 'In past year, did you work overtime or take second job?',
    'm2k2h': 'What kind of school/program are you attending?-Job corps',
    'f4k8': 'What would the hourly wage have to be in order for you to take a job? ($)',
    'f4k7': 'Why aren\'t you looking for a regular job?',
    'f4k6': 'How long have you been looking for a regular job?',
    'f4k5': 'Are you currently looking for a regular job?',
    'f4k3a_8': 'What program/school completed: job corps',
    'm3i23j': 'In past year, did you work overtime or take second job?',
    'm3k3a_13': 'What program/school completed: program to learn job skills?',
    'f2k10b': 'When last worked regular job 2+ weeks for which you got paycheck?-(Year)',
    'm3k3a_14': 'What program/school completed: program to get job?',
    'f2k10a': 'When last worked regular job 2+ weeks for which you got paycheck?-(Month)',
    'f3e8': 'Does CP engage in activities other than regular job for money or necessities?',
    'm3k2_13': 'What program/school: program to learn job skills?',
    'm5i20': 'I20. Range of amount earned from all regular jobs in past 12 months',
    'm3k2_14': 'What program/school: program to get a job?',
    'm5i9a': 'I9A. Month you last worked at a regular job lasting 2 weeks in a row or more',
    'f4k2_8': 'What school/program attending: job corps',
    'm5i9': 'I9. Date you last worked at a regular job lasting 2 weeks in a row or more',
    'm5i8': 'I8. The hourly wage for which you would take a job',
    'm5i21': 'I21. Number of weeks you worked at all regular jobs in past 12 months',
    'm5i7': 'I7. Reason you are not looking for a regular job',
    'm5i6': 'I6. Length of time you have been looking for a regular job',
    'f2k14': 'How many hours (do/did) you usually work per week at (this/that) job?',
    'f2k19': 'During past 12 mons, have you worked more than one regular job at a time?',
    'f4i16a_2': 'What were you required to do: work in a paid job?',
    'f4i16a_3': 'What were you required to do: work in an unpaid job?',
    'm4b19': 'In last two years, had to quit job, school or training because child care?',
    'm5i23': 'I23. Range of regular jobs lasting 2 wks or more you have had in past 12 months',
    'm5f16a_3': 'F16A_3. Required to work in an unpaid job',
    'm5f16a_1': 'F16A_1. Required to look for a job',
    'f3k17b': 'How often true: child care problems are difficult to deal with at job?',
    'f4k3b': 'In the last 2 years, have you taken any classes to improve your job skills?',
    'm5g20': 'Drinking/hangover interfered with work at school/job/home during past 12 months',
    'm4i7f': 'In past 12 months, received help from welfare office or welfare job placement?',
    'f4k2_13': 'What school/program attending: learn job skills',
    'f4k2_14': 'What school/program attending: help get a job',
    'f3k18': 'In past year, did you work more than one job at a time?',
    'f3k12': 'What do/did you do at this/that job?',
    'f3k13': 'About how much do/did you earn in this/that job before taxes? ($)',
    'f3k10': 'How many hours/week do you usually work that job?',
    'f3k8': 'At what hourly wage would you take the job? ($)',
    'f3k5': 'Are you currently looking for a regular job?',
    'f3k6': 'How long have you been looking for a job?',
    'f4i0f_3': 'Attended workshops: finding jobs or job training?',
    'm5i9b': 'I9B. Year you last worked at a regular job lasting 2 weeks in a row or more',
    'm2h14a1': 'What were you required to do?-Look for a job',
    'm5i5': 'I5. You are currently looking for a regular job',
    'm5i22': 'I22. Number of regular jobs lasting 2 wks or more you have had in past 12 months',
    'f3k23': 'In last 3 years, how many regular jobs have lasted 2 or more weeks?',
    'f3k22': 'In last year, how many wks did you work all regular jobs?',
    'f3k20': 'How much did you earn from all regular jobs in last year? ($)',
    'f2k3h': 'What kind of school/program are you attending?-Job corps',
    'f3k3a_14': 'What program/schooling completed: get a job?',
    'm3i7g': 'Since child\'s first birthday: helped by welfare/job placement office?',
    'm4c39': 'Father have problems keeping job, getting along fam/friends b/c alc/drugs?',
    'f4k19': 'How much did you earn from all reg jobs in past 12 months (amount)?',
    'f4k18': 'When you had more than 1 reg job at time, # hrs/wk did you usual work?',
    'f4k13': 'How much you usual earn in job, before taxes and deductions ($)?',
    'f4k12': 'What did you do at this/that job?',
    'f4k11': 'Do you work for yourself or for someone else in this job?',
    'f4k10': 'How many hours do you usually work per week at that job?',
    'f2k20': 'How much did you earn total from all of your regular jobs in past 12 months?',
    'f4i7f': 'In past year, received help from welfare office or welfare job placement?',
    'm2k14a': 'When you worked more than one job, how many hrs a wk total did you work?',
    'f5i19a': 'I19A. Amount earned from all regular jobs in past 12 months',
    'm5i19': 'I19. Amount earned from all regular jobs in past 12 months',
    'f3k3b': 'Since child\'s first birthday, any classes to improve job skills?',
    'm5i19a': 'I19A. Amount earned from all regular jobs in past 12 months',
    'm3e8': 'Does CP do activities other than regular job for money or necessities?',
    'm4i0f_3': 'Attended workshops/sessions at child\'s school on finding jobs or job training?',
    'm4k3a_8': 'What program/school completed: job corps',
    'm4e7a2': 'When part last work job lasting 2 consec weeks+ for reg paycheck (yr)?',
    'm4e7a1': 'When part last work job lasting 2 consec weeks+ for reg paycheck (mo)?',
    'f3k2_13': 'What program/school attending: learn job skills?',
    'f3k2_14': 'What program/school attending: get a job?',
    'm3k16b': 'How often true: Child care problems are difficult to deal with at job?',
    'f5i2_14': 'I2_14. Attending program to help get a job',
    'f5i2_13': 'I2_13. Attending program to learn job skills',
    'm5i14a3': 'I14A3. At your primary job you regularly work nights',
    'f4b19': 'Last 2 yrs, have had to quit job/school/training because probs with care?',
    'f5i2_8': 'I2_8. Attending job corps',
    'f2k15a': 'About how much (do/did) you usually earn in (this/that) job, before taxes? (tota',
    'f2h12a3': 'What were you required to do?-Work in an unpaid job',
    'f2h12a2': 'What were you required to do?-Work in a paid job',
    'm2k9': 'How many hours per week do you usually work at current job?',
    'f4k14a2': 'At your primary job, do you regularly work evenings (6pm-11pm)?',
    'f4k14a3': 'At your primary job, do you regularly work nights (11pm-7am)?',
    'f4k14a1': 'At your primary job, do you regularly work weekdays?',
    'f4k14a4': 'At your primary job, do you regularly work weekends?',
    'f4k14a5': 'At your primary job, do you regularly work different times each week?',
    'f5i18': 'I18. Hrs/week you usually worked altogether while working more than one job',
    'f5i19': 'I19. Amount earned from all regular jobs in past 12 months',
    'f5i13': 'i13. how much you earn in that job, before taxes',
    'f5i11': 'I11. You work for yourself or for someone else in this job',
    'f5i17': 'I17. In past 12 months you worked more than one regular job at the same time',
    'f4e10': 'Does CP have problem keeping job/getting along friends because alc/drugs?',
    'm4k18': 'When you had more than 1 reg job at time, # hrs/wk did you usual work?',
    'm5f16a_2': 'F16A_2. Required to work in a paid job',
    'm4k2_14': 'What school/program attending: program to help get a job',
    'm3i16a_1': 'Required to: look for a job?',
    'm3i16a_2': 'Required to: work in a paid job?',
    'm3i16a_3': 'Required to: work in an unpaid job?',
    'm5d7b': 'D7B. Month current partner last worked at a job',
    'f5i23': 'I23. Range of regular jobs lasting 2 wks or more you have had in past 12 months',
    'f5i22': 'I22. Number of regular jobs lasting 2 wks or more you have had in past 12 months',
    'f5i21': 'I21. Number of weeks you worked at all regular jobs in past 12 months',
    'f5i20': 'I20. Range of amount earned from all regular jobs in past 12 months',
    'm4i23m': 'In past 12 months, you worked overtime or taken a second job?',
    'f5i13p': 'I13P. Unit: Amount you usually earn in this job before taxes/deductions',
    'f2k7f': 'How much did you earn in longest job held when 20?-($ Amount)',
    'f2k7e': 'How many different jobs did you have in the year you were 20?',
    'm5i2_13': 'I2_13. Attending program to learn job skills',
    'm2k3a8': 'What program/schooling have you completed?-Job corps',
    'f1j7bc': 'What sort of work do/did you do in your current/most recent job? - Broad',
    'f5i14a4': 'I14A4. At your primary job you regularly work weekends',
    'f5i3b': 'I3B. You have taken classes to improve job skills since last interview',
    'm4k21': 'In past 12 months how many weeks did you work at your job?',
    'm4k20': 'How much did you earn from all reg jobs in the past 12 months (range)?',
    'm4k23': 'In past 12 months, how many reg jobs have you had that lasted 2 weeks+ (range)?',
    'm4k22': 'In past 12 months, how many reg jobs have you had that lasted 2 weeks or more?',
    'f2k7b8': 'What program/schooling did you attend?-Job corps',
    'm2k10a': 'About how much (do/did) you usually earn in (this/that) job, before taxes?',
    'm4k14a1': 'At your primary job, do you regularly work weekdays?',
    'm4k14a3': 'At your primary job, do you regularly work nights (11pm-7am)?',
    'm4k6': 'How long have you been looking for a regular job?',
    'm4k3a_13': 'What program/school completed: program to learn job skills',
    'm4k14a4': 'At your primary job, do you regularly work weekends?',
    'm5i3a_13': 'I3A_13. Completed program to learn job skills',
    'm3e10': 'Does CP have problems such as keeping a job or friends due to alcohol/drugs?',
    'm5i18': 'I18. Hrs/week you usually worked altogether while working more than one job',
    'm4k14a2': 'At your primary job, do you regularly work evenings (6pm-11pm)?',
    'm4k3b': 'In the last 2 years, have you taken any classes to improve your job skills?',
    'f2k9a': 'How long have you been looking for a regular job?',
    'f2k9c': 'What would the hourly wage have to be for you to take a job?',
    'f2k9b': 'Why aren\'t you looking for a regular job?',
    'm5i3a_8': 'I3A_8. Completed job corps',
    'f2k19a': 'When you worked more than one job,how many hrs a wk altogether did you work?',
    'f2h12': 'Were you required to work/school/look for job/name mother to get benefits?',
    'f3e7a1': 'When did CP last have paid job lasting two consecutive weeks or more? (month)',
    'm5i14a4': 'I14A4. At your primary job you regularly work weekends',
    'm5i14a1': 'I14A1. At your primary job you regularly work weekdays',
    'm5i14a2': 'I14A2. At your primary job you regularly work evenings',
    'm2k2n': 'What kind of school/program are you attending?-Program to help get job',
    'f2k9': 'Are you currently looking for a regular job?',
    'm2k2m': 'What kind of school/program are you attending?-Job skills program',
    'm3k19': 'How much did you earn from all regular jobs in past year? ($)',
    'm3k18': 'When you were working more than one job, how many hours did you work?',
    'm3k10': 'How many hours/week do you usually work that job?',
    'm3k13': 'About how much do/did you earn in this/that job before taxes? ($)',
    'm3k17': 'In past year, did you work more than one job at a time?',
    'm5i3b': 'I3B. You have taken classes to improve job skills since last interview',
    'm4k10': 'How many hours do you usually work per week at that job?',
    'm4k11': 'Do you work for yourself or for someone else in this job?',
    'm4k12': 'What did you do at this/that job?',
    'm4k13': 'How much you usual earn in job, before taxes and deductions? ($)',
    'm4k17': 'Ever time in past 12 months you worked more than 1 regular job at the same time?',
    'm4k19': 'How much did you earn from all reg jobs in past 12 months (amount)?',
    'm5i2_14': 'I2_14. Attending program to help get a job',
    'm5i17': 'I17. In past 12 months you worked more than one regular job at the same time',
    'f5i14a2': 'I14A2. At your primary job you regularly work evenings',
    'f5i14a1': 'I14A1. At your primary job you regularly work weekdays',
    'f5d7a': 'D7A. Month and year current partner last worked at a job',
    'f5d7c': 'D7C. Year current partner last worked at a job',
    'f5d7b': 'D7B. Month current partner last worked at a job',
    'm5i3a_14': 'I3A_14. Completed program to help get a job',
    'm2h14a2': 'What were you required to do?-Work in a paid job',
    'm2h14a3': 'What were you required to do?-Work in an unpaid job',
    'f3k7': 'Why aren\'t you looking for a regular job?',
    'm4k7': 'Why aren\'t you looking for a regular job?',
    'm4k8': 'What would the hourly wage have to be in order for you to take a job? ($)',
    'f3i16a_1': 'Required to: look for a job?',
    'f3i16a_3': 'Required to: work in an unpaid job?',
    'f3i16a_2': 'Required to: work in a paid job?',
    'm5i2_8': 'I2_8. Attending job corps',
    'm4k5': 'Are you currently looking for a regular job?',
    'm4k2_13': 'What school/program attending: program to learn job skills',
    'f5i3a_14': 'I3A_14. Completed program to help get a job',
    'f5i5': 'I5. You are currently looking for a regular job',
    'f5i7': 'I7. Reason you are not looking for a regular job',
    'f5i8': 'I8. The hourly wage for which you would take a job',
    'f5i9': 'I9. Date you last worked at a regular job lasting 2 weeks in a row or more',
    'm2k10bc': 'What do/did you do at this/that job? - broad categories',
    'f3k23a': 'Range of number of these jobs you had in past three years?',
    'f5i8a': 'I8A. The hourly wage for which you would take a job',
    'm5d7c': 'D7C. Year current partner last worked at a job',
    'f1j11': 'In last yr, how many wks did you spend at your regular job?',
    'f1j10': 'How much did you earn from all of your jobs in the last year?',
    'f1j12': 'When at these jobs, how many hours per week did you usually work?',
    'm3k5': 'Are you currently looking for a regular job?',
    'm3k7': 'Why aren\'t you looking for a regular job?',
    'm3k6': 'How long have you been looking for a job?',
    'm3k8': 'At What hourly wage would you take the job? ($)',
    'm5d7a': 'D7A. Month and year current partner last worked at a job',
    'f2k15bc': 'What do/did you do at this/that job? - broad categories',
    'f5i9b': 'I9B. Year you last worked at a regular job lasting 2 weeks in a row or more',
    'f5i9a': 'I9A. Month you last worked at a regular job lasting 2 weeks in a row or more',
    'm3k21': 'In past year, how many wks did you work all regular jobs?',
    'm3k22': 'In past 3 years, how many regular jobs for 2 or more weeks?',
    'f4k22': 'In past year, how many reg jobs have you had that lasted 2 weeks or more?',
    'f4k23': 'In past year, how many reg jobs have you had that lasted 2 weeks+ (range)?',
    'm1d2b': 'How imp for successful marriage, husband has steady job?',
    'm5i13p': 'I13P. Unit: Amount you usually earn in this job before taxes/deductions',
    'm5i8a': 'I8A. The hourly wage for which you would take a job',
    'm4e7': 'What current partner doing last week-working reg job, school, or sthg else?',
    'f3k3a_8': 'What program/school completed: job corps?',
    'f2k7c': 'During the year after your 20th birthday, did you have full-time job?',
    'f4k3a_14': 'What program/school completed: help get a job',
    't5f1d': 'F1D. I really enjoy may present teaching job',
    'm2k15a': 'How much did you earn, last 12 mons, from all on-books jobs?-($ Range)',
    'f5i3a_13': 'I3A_13. Completed program to learn job skills',
    'f4k20': 'How much did you earn from all reg jobs in the past 12 months (range)?',
    'f4k21': 'In past year, how many weeks did you work at your job?',
    'm3k3a_8': 'What program/school completed: job corps?',
    'm2c35': 'Does father have probs keeping job/getting along because of drugs/alcohol?',
    'm3b24': 'Have you quit job/school because of child care problems?',
    'f2k7b14': 'What program/schooling did you attend?-Program to help get job',
    'f2k7b13': 'What program/schooling did you attend?-Job skills program',
    'f4k13p': 'How much you usual earn in job, before taxes and deductions (time period)?',
    'm2k15': 'How much did you earn total from all on-the-books jobs in past 12 months?',
    'f3k3a_13': 'What program/schooling completed: learn job skills?',
    'm3k3b': 'Since child\'s 1st birthday, any classes to improve job skills?',
    'f1j5a': 'In what mo did you last work regular job lasting 2+wks?',
    'f1j5b': 'In what yr did you last work regular job lasting 2+wks?',
    'm2b35b': 'Since child\'s birth did you have to quit school/job due to lack of care?',
    'm2k3a14': 'What program/schooling have you completed?-Program to help get job',
    'f2k3n': 'What kind of school/program are you attending?-Program to help get job'
}

MORTGAGE = {
    'f4i23d': 'In past 12 months, did not pay full amt rent/mortgage payments b/c wasn\'t enough',
    'f4i23e': 'In past 12 months, evicted from home or apt for not paying the rent or mortgage?',
    'm4i23e': 'In past 12 months, evicted from home or apt for not paying the rent or mortgage?',
    'f4i3b1': 'Whose name is on the mortgage for this house?',
    'f5f3b': 'F3B. Monthly mortgage payments including taxes/insurance that are included',
    'f3i3b': 'What are the monthly mortgage payments? ($)',
    'm5f3b': 'F3B. Monthly mortgage payments',
    'f3i3b1': '18C ONLY: Whose name is on the mortgage?',
    'm5f3b1': 'F3B1. Name on the mortgage for this house',
    'm3i23b': 'In past year, did you not pay full rent or mortgage?',
    'f4i3b': 'What are your monthly mortgage payments?',
    'f3i23b': 'In past year, did you not pay full rent or mortgage ?',
    'm3i3b': 'What are the monthly mortgage payments?',
    'm2h3b': 'What is the monthly mortgage payment(Incl Taxes & Insurance)?',
    'm5f23c': 'F23C. Did not pay full amount of rent/mortgage payments in past 12 months',
    'm2h19e': 'In past 12 months, did you-Get evicted for not paying rent/mortgage?',
    'f2h17d': 'In past 12 months, did you-Not pay full amount of rent/mortgage?',
    'f2h17e': 'In past 12 months, did you-Get evicted for not paying rent/mortgage?',
    'm4i23d': 'In past 12 months, did not pay full amt rent/mortgage payments b/c wasn\'t enough',
    'f2h3b': 'What are the monthly mortgage payments(Incl Taxes & Insurance)?',
    'n5g1c': 'G1C. Rent or mortgage was not paid because not enough money',
    'n5g1d': 'G1D. Evicted from home or apartment for not paying rent or mortgage',
    'm3i3b1': '18C ONLY: Whose name is on the mortgage?',
    'f5f3b1': 'F3B1. Name on the mortgage for this house',
    'm4i3b1': 'Whose name is on the mortgage for this house?',
    'm4i3b': 'What are your monthly mortgage payments?',
    'm2h19d': 'In past 12 months, did you-Not pay full amount of rent/mortgage?',
    'f1k4': 'What are your mo expenses for rent or mortgage?',
    'f5f23c': 'F23C. Did not pay full amount of rent/mortgage payments in past 12 months'
}

BOYFRIEND = {
    'm3h2a_6': 'Who gave help: boyfriend/partner?',
    'm3b8a_2': 'What arrangements: mother\'s partner or boyfriend?',
    'm2g5a6': 'Who gave you financial help/money?-Boyfriend/partner',
    'f2b21a2': 'What care arrangement(s) are you using now?-mother\'s partner/boyfriend',
    'm4h2a_6': 'Who gave help: boyfriend/partner',
    'm5e2a_6': 'E2A_6. Boyfriend/partner gave financial help',
    'm2b25a2': 'What care arrngement are you using now?-Mother\'s partner/boyfriend'
}

DISAB = {
    'm2b4h': 'What type of physical disability?-Other',
    'm2b4c': 'What type of physical disability?-Partial blindness',
    'f5f7_102': 'f7_102. SSI/disability',
    't5c2': 'C2. Child\'s primary disability as identified on IEP',
    'f1k2b': 'How much money did you receive from Unemployment/SS/Disability?',
    'kind_a13': '-->a13. child has diagnosed disability',
    'kind_a14': '-->a14. child has an iep for disability',
    'f2b4d': 'What type of physical disability?-Total deafness',
    'f1k1b': 'In last yr, did you have income from unemp.ins,ss,disability?',
    'm2b4g': 'What type of physical disability?-Problems with limbs',
    'f2b3': 'Does child have any physical disabilities?',
    'm2b4b': 'What type of physical disability?-Total blindness',
    'p5q3bb_104': 'Q3BB_104. Child has learning disability without known cause',
    'm2b4a': 'What type of physical disability?-Cerebral Palsy',
    'm2b3': 'Does child have any physical disabilities?',
    'm2b4d': 'What type of physical disability?-Total deafness',
    'm2b4e': 'What type of physical disability?-Partial deafness',
    'm2b4f': 'What type of physical disability?-Down\'s syndrome',
    'm1j1c': 'In last yr did you have income from Unem.ins/wkmn comp/disability/SS?',
    'f2b4c': 'What type of physical disability?-Partial blindness',
    'f2b4b': 'What type of physical disability?-Total blindness',
    'f2b4a': 'What type of physical disability?-Cerebral Palsy',
    'f2b4f': 'What type of physical disability?-Down\'s syndrome',
    'f2b4e': 'What type of physical disability?-Partial deafness',
    'f2b4h': 'What type of physical disability?-Other',
    'm1j2c': 'In last 12 mo, about how much money did you receive from unemployment/SS/disabil',
    'f2b4g': 'What type of physical disability?-Problems with limbs'
}

PREGNAN = {
    'f1b6d': 'When last tgthr, how often did you disagree about the pregnancy?',
    'm2e9a2': 'Did this happen during your pregnancy?',
    'm2e9a1': 'Did this happen before you were pregnant?',
    'm2d9a1': 'Were you cut/bruised/hurt before you were pregnant?',
    'm1b6d': 'When you and BF tgthr how often did you disagree about the pregnancy?',
    'm1b23d': 'In last mo, how often did you and BF disagree on pregnancy?',
    'm1b12d': 'In last mo, how often did you and BF disagree about the pregnancy?',
    'f1b23d': 'In last mo, how often did you disagree about the pregnancy?',
    'f4i23p6': 'Agree/disagree: Welfare discourages women who get pregnant from marrying father',
    'm1b1b': 'How many months did you know Baby\'s Father before you got pregnant?',
    'm1b1a': 'How many years did you know Baby\'s Father before you got pregnant?',
    'm1b27': 'When you found out you were pregnant, did you think about having an abortion?',
    'm1b26': 'After you found out you were pregnant,how did your relationship with BF changed?',
    'm3a15': 'Did you ever get pregnant in any of these relationships?',
    'm4a16': 'In last 2 yrs, you had any pregnanc end in miscarriage/stillbirth/abortion?',
    'm4a15': 'Did you ever get pregnant in any of these relationships?',
    'm2d9a2': 'Were you cut/bruised/hurt during your pregnancy?',
    'm1a13': 'Did you visit a doctor/other health care professional to check on the pregnancy?',
    'm2f6': 'Since child born, have you had another baby/are you pregnant now?',
    'm3a10': 'Have you had another baby, adopted a child, or are now pregnant?',
    'm5g2a_106': 'G2A_106. Pregnant',
    'f1b1a': 'How many years did you know each other before (baby\'s mother) got pregnant?',
    'f1b1b': 'How many months did you know each other before (baby\'s mother) got pregnant?',
    'f3a15': 'Did you get any of these partners pregnant?',
    'f1b12d': 'In last mo how often, disagree about the pregnancy?',
    'f4a15': 'Did you get any of these partners pregnant?',
    'm1a13a': 'In which month of pregnancy did you 1st see doctor/other health care provider?',
    'm4i23p6': 'Agree/disagree: Welfare discourages women who get pregnant from marrying father'
}

EMPLOY = {
    'f1j9': 'Did/does your employer provide health insurance?',
    'f3c41': 'Is mother currently working, in school, or unemployed?',
    'm3b16a4': 'How much money does [employer] give you? ($)',
    'f3b16a4': 'How much money does [employer] give you? ($)',
    'f1e1e8': 'People who currently live in your HH - 8th employment?',
    'f1e1e1': 'People who currently live in your HH - 1st employment?',
    'f1e1e2': 'People who currently live in your HH - 2nd employment?',
    'f1e1e3': 'People who currently live in your HH - 3rd employment?',
    'f1e1e4': 'People who currently live in your HH - 4th employment?',
    'f1e1e5': 'People who currently live in your HH - 5th employment?',
    'f1e1e6': 'People who currently live in your HH - 6th employment?',
    'f1e1e7': 'People who currently live in your HH - 7th employment?',
    'p5h14b_3': 'H14B_3. Insurance through PCG\'s employer',
    'p5h14b_6': 'H14B_6. Insurance through employer of partner who is not bioparent',
    'f3j4b_3': 'How purchased plan: through respondent\'s employer?',
    'f3j4b_5': 'How purchased plan: through partner\'s employer?',
    'f3j4b_4': 'How purchased plan: through child\'s mother\'s employer?',
    'm4i7e': 'In the past 12 months, have you received help from an employment office?',
    'm2b30d': 'Who provides financial assistance for child care?-Employer',
    'n5e2': 'E2. Current employment status',
    'f2h8a3': 'In past 12 months, have you received unemployment/wrkms comp?',
    'f3i7b': 'Since child\'s first birthday, helped by employment office?',
    'f3b15_4': 'Who helps: employer?',
    'm5f7a': 'F7A. Received help from an employment office in past 12 months',
    'm3c41': 'Is father currently working, in school, or unemployed?',
    'p5h14b_4': 'H14B_4. Insurance through child\'s father\'s employer',
    'f2j4b3': 'Who purchased the health insurance plan?-Through respondent\'s employer',
    'f2j4b4': 'Who purchased the health insurance plan?-Through child\'s mother\'s employer',
    'f2j4b5': 'Who purchased the health insurance plan?-Thru partner\'s employer',
    'f2b26d': 'Who provides financial assistance for child care?-Employer',
    'm3b15_4': 'Who helps: employer?',
    'm2j4b5': 'How did you get private plan? Through partner\'s employer?',
    'm2j4b3': 'How did you get private plan?-Through respondent\'s employer',
    'f1k2b': 'How much money did you receive from Unemployment/SS/Disability?',
    'm4j4b_5': 'How did you purchase this plan: partner\'s employer',
    'm4j4b_4': 'How did you purchase this plan: child\'s father\'s employer',
    'm4j4b_3': 'How did you purchase this plan: respondent\'s employer',
    'p5h14b_5': 'H14B_5. Insurance through child\'s mother\'s employer',
    'f4k3c': 'In the last 2 years, have you received any kind of employment counseling?',
    'm3j4b_3': 'Who purchased plan: through respondent\'s employer',
    'm3j4b_5': 'Who purchased plan: through partner\'s employer',
    'm3i7f': 'Since child\'s first birthday: helped by employment office?',
    'f4j4b_5': 'How did you purchase this plan: through partner\'s employer',
    'f4i7e': 'In the past year, have you received help from an employment office?',
    'f3k3c': 'Since child\'s first birthday, received employment counseling?',
    'm2j4b4': 'How did you get private plan?-Through child\'s father\'s employer',
    'm5i3c': 'I3C. You received any kind of employment counseling since last interview',
    'm4k3c': 'In the last 2 years, have you received any kind of employment counseling?',
    'n5d3e_8': 'D3E_8. Employment status of 8th person in household',
    'f2b27d': 'How much money does employer give you? ($)',
    'm2b31d': 'How much money does employer give you? ($)',
    'm1e1e8': 'People who currently live in your HH - 8th employment?',
    'm2h8f': 'Since child\'s birth,have you received help from-Employment agency?',
    'm2c33': 'Is father currently working/in school/unemployed/in jail?',
    'f5f7a': 'F7A. In the past twelve months, you received help from an employment office',
    'm1e1e3': 'People who currently live in your HH - 3rd employment?',
    'm1e1e2': 'People who currently live in your HH - 2nd employment?',
    'f4j4b_3': 'How did you purchase this plan: through respondent\'s employer',
    'f4j4b_4': 'How did you purchase this plan: through child\'s father\'s employer',
    'm2h9a3': 'In past 12 months, have you received other help?(unemployment/wrkms comp/etc)',
    'm4e8': 'Does part do anythg other than reg paid employ to make money/other necessities?',
    'm1e1e5': 'People who currently live in your HH - 5th employment?',
    'm1e1e4': 'People who currently live in your HH - 4th employment?',
    'm1e1e7': 'People who currently live in your HH - 7th employment?',
    'm1e1e6': 'People who currently live in your HH - 6th employment?',
    'm1e1e1': 'People who currently live in your HH - 1st employment?',
    'f2h7a': 'Since child\'s birth, have you received help from-employment/welfare agency?',
    'm1j2c': 'In last 12 mo, about how much money did you receive from unemployment/SS/disabil',
    'm3j4b_4': 'Who purchased plan: through child\'s father\'s employer',
    'n5d3e_7': 'D3E_7. Employment status of 7th person in household',
    'n5d3e_6': 'D3E_6. Employment status of 6th person in household',
    'n5d3e_5': 'D3E_5. Employment status of 5th person in household',
    'n5d3e_4': 'D3E_4. Employment status of 4th person in household',
    'n5d3e_3': 'D3E_3. Employment status of 3rd person in household',
    'n5d3e_2': 'D3E_2. Employment status of 2nd person in household',
    'n5d3e_1': 'D3E_1. Employment status of 1st person in household',
    'f5i3c': 'I3C. You received any kind of employment counseling since last interview',
    'm3k3c': 'Since child\'s 1st birthday, received employment counseling?'
}

GUN = {
    'kind_f4d': '-->f4d. gunshot noise',
    'o5c10a_10': 'C10A_10. Weapons (guns or knives) within reach of children observed inside home',
    't5f4d': 'F4D. How much of a problem is gunshot noise in the neighborhood'
}

DRUG = {
    'f3c44': 'Does mother have problems with job/family/friends because of alcohol/drug use?',
    'f3j44k': 'In past year, how often used those drugs?',
    'm3j43b_5': 'Was therapy for: drug use problems',
    'm1i9': 'Does BF have a problem keeping a job/friends because of drugs/alc use?',
    'm4i26b_3': 'What charges do you currently have pending? possession/use/sale drugs',
    'm4c37a_3': 'What father in jail for: possession/use/sale marijuana/cocaine/other drugs',
    'f3j45': 'In past year, did your drug use interfere with life?',
    'f3j46': 'In past year, were you under influence of drugs in dangerous situation?',
    'f3j47': 'In past year, had any emotional/psych. problems from drugs?',
    'm3j37a': 'How often did drug use interfere with work/school/home life?',
    'm3j36j': 'Did respondent use one/more drugs?',
    'f2h21d12': 'What charges were you convicted of ?-Possession of other illicit drugs',
    'f2h21d13': 'What charges were you convicted of ?-Sale/maufacture of other illicit drugs',
    'm3j48': 'Did bio. father have problems with drinking or drugs?',
    'm3j53': 'Did bio. mother have problems with drinking/drugs?',
    'm4k25c': 'During those weeks, how many hrs/wk did you engage in drugs/prostitution/hustles',
    'f4j22j': 'INT CHK: DID RESPONDENT USE ONE OR MORE DRUGS?',
    'f4j22k': 'In the past 12 months, how often did you use any of those drugs?',
    'm2c36a12': 'What was father in jail for?-Possession of other illicit drugs',
    'm3k26f_4': 'What payment for drugs/prostitution: other?',
    'm4e10': 'Partner have probs keeping job/getting along w/family/friends b/c alcohol/drug?',
    'm3j53b': 'Was she ever hospitalized for her drinking/drug use?',
    'm1b23e': 'In last mo, how often did you and BF disagree on drug/alco use?',
    'f5f26b2_4': 'F26B2_4. Possession/use/sale of illicit drugs',
    'm3i26b_3': 'Charges pending: possession/use/sale of drugs?',
    'f3j48': 'In past year, did you have such a strong desire you had to use drugs?',
    'f3j49': 'In past year, was there a period that you spent lots of time using drugs?',
    'f5g23a_5': 'G23A_5. Counseling or therapy for drug use problems',
    'm3j53a': 'Did she ever get professional treatment for drinking/drug problem?',
    'm1b12e': 'In last mo, how often did you and BF disagree about drug/alc use?',
    'f1b23e': 'In last mo, how often did you disagree about drinking/drug use?',
    'f4j34': 'INT CHK: DID BIOLOGICAL MOTHER HAVE PROBLEMS WITH DRINKING OR DRUGS?',
    'f2h20b13': 'What charges do you have pending ?-Sale/manufacture of other illicit drugs',
    'f2h20b12': 'What charges do you have pending ?-Possession of other illicit drugs',
    'm1b10b8': 'Reasons aren\'t married now, Drug problem?',
    'm3c44': 'Does father have problems with job/family/friends because of alcohol/drug use?',
    'm3j36k': 'In past year, how often did you use drugs?',
    'm2k19f1b': 'What else did you get for selling drugs/protitution?-Clothing',
    'm5g23a_5': 'G23A_5. Counseling or therapy for drug use problems',
    'm4j34': 'INT CHK: DID BIOLOGICAL MOTHER HAVE PROBLEMS WITH DRINKING OR DRUGS?',
    'f2k24e1': 'How much did you recv past 12 mons from selling drugs/prostitution?-($ Range)',
    'o5a6e': 'A6E. Alcohol or drug paraphernalia',
    'm4j34a': 'Did she ever get professional treatment for her drinking/drug problem?',
    'm4j34b': 'Was she ever hospitalized for her drinking/drug use?',
    'm3a8b_6': 'Why relationship ended: drug or alcohol problem?',
    'm3i28_3': 'Charges convicted: possession/use/sale of drugs?',
    'f3e10': 'Does CP have problems such as keeping job/friends due to alcohol/drugs?',
    'cm3drug_case': 'Constructed - Mother drug dependence (CIDI)',
    'm2j11': 'Since child\'s birth, have you sought help/been treated for drug/alcohol problem?',
    'm2j10': 'Since child\'s birth,has drinking/drugs interfered w/your personal relationships?',
    'cf3drug_case': 'Constructed - Father drug dependence (CIDI)',
    'm5b32': 'B32. Father has problems because of alcohol or drug use',
    'm3j37': 'In past year, did drug use interfere with work/school/home life?',
    'm3j39': 'In past year, had any emotional/psychological problems from drugs?',
    'm1b9b8': 'Reasons aren\'t living tgthr, Drug problem ?',
    'm5i25c': 'I25C. Number of hrs/week during those weeks you sold drugs/prostitution/hustles',
    'f5i25c': 'I25C. Number of hrs/week during those weeks you sold drugs/prostitution/hustles',
    'm3k26e1': 'Range of eanings from selling drugs/prostitution in past year',
    'f5i25b': 'I25B. Number of weeks you sold drugs/prostitution/hustles during last 12 months',
    'f5i25a': 'I25A. You sold drugs/prostitution/hustles during past 12 months',
    'f5i25e': 'I25E. Amount received in last 12 months for selling drugs/prostitution/hustles',
    'f5i25d': 'I25D. Paid in cash or received something else when you sold drugs/prostitution/h',
    'm5f26b2_4': 'F26B2_4. Possession/use/sale of illicit drugs',
    'f3j44j': 'INT CHK: DID RESPONDENT USE ONE OR MORE DRUGS?',
    'm5d10': 'D10. Current partner has problems because of alcohol or drug use',
    'f4j29': 'INT CHK: DID BIOLOGICAL FATHER HAVE PROBLEMS WITH DRINKING OR DRUGS?',
    'f2j8': 'In past month, did you use cocaine/crack/speed/LSD/heroin/other hard drug?',
    'm1b10a8': 'Reason no plan to marry, Drug problem?',
    'm2a9f': 'Why did relationship end? Drug or alcohol problem',
    'm3c42a_3': 'Why is/was father in jail: possession/use/sale of drugs?',
    'm5a6g01_104': 'A6G01_104. Mother had drug problems',
    'm3j52a': 'Did she abuse prescription drugs like valium/sleeping pills?',
    'm5i25b': 'I25B. Number of weeks you sold drugs/prostitution/hustles during last 12 months',
    'f3j50a': 'How often did you use more drugs for longer than intended?',
    'f1g6': 'Have you ever sought help for drugs/alcohol problems?',
    'f1g3': 'In the past 3 months, how often did you use drugs?',
    'f2k24b': 'In past 12 mons, how many weeks did you sell drugs/prostitute/hustle',
    'n5a11_10': 'A11_10. Child not living with BioF because father has drug/alcohol problems',
    'o5g6e': 'G6E. Parent/PCG appeared to be on drugs',
    'm3k26d': 'When selling drugs/prostituting, did you receive cash/something else?',
    'm4j24b_5': 'Was this counseling or therapy for drug use problems?',
    'm3k26b': 'In past year, how many weeks did you sell drugs/prostitute/hustle',
    'm3k26a': 'In past year, did you sell drugs/engage in prostitution/other hustles?',
    'f3j61a': 'Did she ever get professional treatment for drinking/drug problem?',
    'm4j29': 'INT CHK: DID BIOLOGICAL FATHER HAVE PROBLEMS WITH DRINKING OR DRUGS?',
    'm5a6g02_104': 'A6G02_104. Mother had drug problems',
    'm5f28a_4': 'F28A_4. Possession/use/sale of illicit drugs',
    'f5b32x': 'B32X. Mother has problems because of alcohol or drug use',
    'm1b4e': 'Why did rom rel end with (BF), Drug problem ?',
    'f2k24f1d': 'What did you get for selling drugs/protitution?-Other',
    'f2k24f1b': 'What did you get for selling drugs/protitution?-Clothing',
    'f2k24f1c': 'What did you get for selling drugs/protitution?-Place to live',
    'f2k24f1a': 'What did you get for selling drugs/protitution?-Meals',
    'f3j56b': 'Was he ever hospitalized for his drinking/drug use?',
    'f3j56a': 'Did he ever get professional treatment for his drinking/drug problem?',
    'f5b26x_4': 'B26X_4. Possession/use/sale of illicit drugs',
    'm3j43': 'In past year, ever had to use more drugs to get same effect?',
    'm3j42': 'In past year, used more drugs/for longer time than intended?',
    'm3j41': 'In past year, had period of a mth when you spent a lot of time using drugs?',
    'm3j38': 'In past year, were you under influence of drugs in dangerous situation?',
    'f3i26b_3': 'Charges pending: possession/use/sale of drugs?',
    'm4c39': 'Father have problems keeping job, getting along fam/friends b/c alc/drugs?',
    'm1b6e': 'When you and BF tgthr how often did you disagree about alcoh/drug use?',
    'm2k19f1c': 'What else did you get for selling drugs/protitution?-Place to live',
    'f3j51b_5': '18C ONLY: Was therapy for: drug use problems?',
    'f4j33a': 'Did she ever abuse prescription drugs (valium, sleeping pills, or diet pills)?',
    'f4j33b': 'Did she ever have a problem with illegal drugs?',
    'f2k24c': 'In past 12 mons, how many hrs per wk did you sell drugs/protitue/hustle?',
    'f4c37a_3': 'What is/was mother in jail for: illicit drugs?',
    'f5i25e1': 'I25E1. Range received in last 12 months for selling drugs/prostitution/hustles',
    'n5a9_9': 'A9_9. Child not living with BioM because mother has drug/alcohol problems',
    'f3j55b': 'Did he ever have a problem with illegal drugs?',
    'f3j55a': 'Did he ever abuse prescription drugs like valium/sleeping pills?',
    'm2c36a13': 'What was father in jail for?-Sale/manufacture other illicit drugs',
    'f3c42a_3': 'Why mother in jail: possession/use/sale of drugs?',
    'f1b9b8': 'Reasons aren\'t living tgthr, Drug problem?',
    'f4e10': 'Does CP have problem keeping job/getting along friends because alc/drugs?',
    'm4j22k': 'In the past 12 months, how often did you use any of those drugs?',
    'm4j22j': 'INT CHK: DID RESPONDENT USE ONE OR MORE DRUGS?',
    'm2j8': 'In past month, did you use cocaine/crack/speed/LSD/heroin/other hard drug?',
    'f1g5': 'In the past year, has drinking/drugs interfered with work/relationships?',
    'f5a4k_6': 'A4K_6. Drug or alcohol problem',
    'm3j42a': 'How often used more drugs/for longer than intended?',
    'm5a3a1_101': 'A3A1_101. Mother had drug/alcohol issues',
    'm4j33a': 'Did she ever abuse prescrip drugs (valium, sleeping pills, or diet pills)?',
    'f2j10': 'Since child\'s birth,has drinking/drugs interfered w/your personal relationships?',
    'f2j11': 'Since child\'s birth, have you sought help/been treated for drug/alcohol problem?',
    'f1b9a8': 'Reasons no plan to live tgthr, Drug problem?',
    'f1b10a8': 'Reasons no plan to marry, Drug problem?',
    'f4k25a': 'During past yr did you sell/deliver drugs, engage in prostitute, other hustles?',
    'f4k25b': 'In last yr, how many weeks you sell/deliver drugs, prostitution, other hustles?',
    'f4k25c': 'During those weeks, how many hrs/wk did you engage in drugs/prostitution/hustles',
    'f4j34a': 'Did she ever get professional treatment for her drinking/drug problem?',
    'f4j34b': 'Was she ever hospitalized for her drinking/drug use?',
    'f3k26d': 'When selling drugs/prostituting,did you receive cash/something else?',
    'f3k26b': 'In past year, how many weeks did you sell drugs/prostitute/hustle',
    'f3k26c': 'In past year, how many hrs/week did you sell drugs/prostitute/hustle?',
    'f3k26a': 'In past year, did you Sell drugs/engage in prostitution/other hustle?',
    'f5g21k': 'G21K. Frequency you used those drugs in past 12 months',
    'm3k26f_1': 'What payment for drugs/prostitution: meals?',
    'm5i25e': 'I25E. Amount received in last 12 months for selling drugs/prostitution/hustles',
    'f4i26b_3': 'What charges pending: possession/use/sale marijuana/cocaine/drugs',
    'm4j29a': 'Did he ever get professional treatment for his drinking/drug problem?',
    'f3a8b_6': 'Why relationship ended: drug or alcohol problem',
    'm2k19f1d': 'What else did you get for selling drugs/protitution?-Other',
    'm2k19f1a': 'What else did you get for selling drugs/protitution?-Meals',
    'm4k25a': 'During past yr did you sell/deliver drugs,engage in prostitut, other hustles?',
    'm4k25b': 'In last yr, how many weeks you sell/deliver drugs, prostitution, other hustles?',
    'm3j47a': 'Did he abuse prescription drugs like valium/sleeping pills?',
    'm2k19a': 'In past 12 mths, did you-Sell drugs/engage in prostitution/other hustles?',
    'f1b10b8': 'Reasons aren\'t married now, Drug problem?',
    'f3j45a': 'How often did your drug use interfered with your life?',
    'm3e10': 'Does CP have problems such as keeping a job or friends due to alcohol/drugs?',
    'm2j9': 'Since child\'s birth, has drinking/drugs interfered w/how you manage daily?',
    'm3j47b': 'Did he have a problem with illegal drugs?',
    'f2j9': 'Since child\'s birth, has drinking/drugs interfered w/how you manage daily?',
    'f5d10': 'D10. Current partner has problems because of alcohol or drug use',
    'p5q3cx': 'Q3CX. Child uses alcohol or drugs for nonmedical purposes',
    'f3k26e1': 'Range of earnings from selling drugs/prostitution in past year?',
    'f3k26f_5': 'What payment for selling drugs/prostitution: child care?',
    'f3k26f_4': 'What payment for selling drugs/prostitution: other?',
    'f3k26f_3': 'What payment for selling drugs/prostitution: place to live?',
    'f3k26f_2': 'What payment for selling drugs/prostitution: clothing?',
    'f3k26f_1': 'What payment for selling drugs/prostitution: meals?',
    'm3k26f_3': 'What payment for drugs/prostitution: place to live?',
    'm3j52b': 'Did she ever have a problem with illegal drugs?',
    'm2j8a': 'How often in past month did you use hard drugs?',
    'm4i28_3': 'What charges were you convicted of? possession/use/sale drugs',
    'kind_f4c': '-->f4c. selling or using drugs in public',
    'm4j33b': 'Did she ever have a problem with illegal drugs?',
    'm1g3': 'During the preg, how often did you use drugs?',
    'm1g5': 'In past yr has alc/drugs interfered with your work/relationships?',
    'm1g6': 'Have you ever sought help or been treated for drug/alc problems?',
    'm4j28a': 'Did he ever abuse prescrip drugs (valium, sleeping pills, or diet pills)?',
    'm5a6g03_104': 'A6G03_104. Mother had drug problems',
    'm2k19e1': 'How much did you receive past 12 mths from selling drugs/prostitution?-($ Range)',
    'f5f28a_4': 'F28A_4. Possession/use/sale of illicit drugs',
    'm4j28b': 'Did he ever have a problem with illegal drugs?',
    'f4a8b_6': 'Why did relationship end: drugs or alcohol?',
    'f1b12e': 'In last mo how often, disagree about drinking/drug use?',
    'f3i28_3': 'Charges convicted: possession/use/sale of drugs?',
    'f2a8f': 'Why did relationship end? Drug or alcohol problem',
    'm3j40': 'In past year, had such a strong desire, you had to use drugs?',
    'f1j13c': 'Selling stolen goods, selling/delivering drugs, or other hustles?',
    't5f4c': 'F4C. How much of a problem is selling/using drugs or drinking in neighborhood',
    'f4i28_3': 'What charges convicted: possession/use/sale marijuana/cocaine/drugs',
    'm4a8b_6': 'Why relationship ended: drug or alcohol problem?',
    'm3k26f': 'Was other type of payment received for selling drugs/prostitution?',
    'm3k26e': 'How much did you get in past year from selling drugs/prostitution? ($)',
    'm3k26c': 'In past year, how many hrs/week did you sell drugs/prostitute/hustle?',
    'f4j28a': 'Did he ever abuse prescription drugs (valium, sleeping pills, or diet pills)?',
    'f4j28b': 'Did he ever have a problem with illegal drugs?',
    'f3j61b': 'Was she ever hospitalized for her drinking/drug use?',
    'm2k19d': 'When selling drugs/prostituting,did you receive cash or something else?',
    'm2k19e': 'How much did you receive past 12 mths from selling drugs/prostitution?',
    'm2k19f': 'Was other type of payment received for selling drugs/prostitution?',
    'm2k19b': 'In past 12 mths, how many weeks did you sell drugs/prostitute/hustle',
    'm2k19c': 'In past 12 mths, how many hrs per wk did you sell drugs/protitue/hustle?',
    'o5c14': 'C14. Obvious signs of recent alcohol/non-prescription drug consumption inside ho',
    'f3k26e': 'How much did you get in past year from selling drugs/prostitution? ($)',
    'f2k24a': 'In past 12 mons, did you-Sell drugs/engage in prostitution/other hustles?',
    'f2k24e': 'How much did you receive past 12 mons from selling drugs/prostitution?',
    'f2k24d': 'When selling drugs/prostituting,did you receive cash or something else?',
    'f2k24f': 'Was other type of payment received for selling drugs/prostitution?',
    'f4j29b': 'Was he ever hospitalized for his drinking/drug use?',
    'f4j29a': 'Did he ever get professional treatment for his drinking/drug problem?',
    'f3j60b': 'Did she ever have a problem with illegal drugs?',
    'f3j60a': 'Did she ever abuse prescription drugs like valium/sleeping pills?',
    'm1b9a8': 'Reasons no plan to live tgthr, Drug problem ?',
    'm3k26f_5': 'What payment for drugs/prostitution: child care?',
    'm3k26f_2': 'What payment for drugs/prostitution: clothing?',
    'f3j61': 'INT CHK: DID BIO. MOTHER HAVE A PROBLEM WITH DRINKING OR DRUGS?',
    'm2c35': 'Does father have probs keeping job/getting along because of drugs/alcohol?',
    'm5i25e1': 'I25E1. Range received in last 12 months for selling drugs/prostitution/hustles',
    'f2j8a': 'How often in past month did you use hard drugs?',
    'm5b30a1_4': 'B30A1_4. Possession/use/sale of illicit drugs',
    'f4j24b_5': 'Was this counseling or therapy for drug use problems?',
    'm3j48a': 'Did bio. father he ever get prof treatment for drinking/drug problem?',
    'm3j48b': 'Was bio. father hospitalized for his drinking/drug use?',
    'm5i25d': 'I25D. Paid in cash or received something else when you sold drugs/prostitution/h',
    'm5i25a': 'I25A. You sold drugs/prostitution/hustles during past 12 months',
    'f1b4e': 'Why did romantic rel end with BM, Drug problem ?',
    'f3j56': 'INT CHK: DID BIO. FATHER HAVE PROBLEM WITH DRINKING OR DRUGS?',
    'f3j51': 'In past year, did you ever use more drugs to get same effect?',
    'f3j50': 'In past year, used more drugs for longer time than intended?',
    'm4j29b': 'Was he ever hospitalized for his drinking/drug use?',
    'm5g21k': 'G21K. Frequency you used those drugs in past 12 months'
}

WEAPON = {
    'm5f26b2_8': 'F26B2_8. Weapons',
    'm5b30a1_8': 'B30A1_8. Weapons',
    'm5f28a_8': 'F28A_8. Weapons',
    'f5b26x_8': 'B26X_8. Weapons',
    'f5f28a_8': 'F28A_8. Weapons',
    'f5f26b2_8': 'F26B2_8. Weapons',
    'o5c10a_10': 'C10A_10. Weapons (guns or knives) within reach of children observed inside home',
    'p5m5b': 'M5B. In past year how often did you see person attacked with weapon'
}


ABUS = {
    'f5f28a_10': 'F28A_10. Domestic violence or child abuse',
    'f3a8b_7': 'Why relationship ended: violence/abuse',
    'm1b9b9': 'Reasons aren\'t living tgthr, Violence, abuse ?',
    'm1b10b9': 'Reasons aren\'t married now, Violence, abuse?',
    'm1b10a9': 'Reason no plan to marry, Violence, abuse?',
    'm3j52a': 'Did she abuse prescription drugs like valium/sleeping pills?',
    'm1b9a9': 'Reasons no plan to live tgthr, Violence, abuse ?',
    'f4j33a': 'Did she ever abuse prescription drugs (valium, sleeping pills, or diet pills)?',
    'f1b9a9': 'Reasons no plan to live tgthr, Violence, abuse?',
    'f3j55a': 'Did he ever abuse prescription drugs like valium/sleeping pills?',
    'f5b26x_10': 'B26X_10. Domestic violence or child abuse',
    'f1b9b9': 'Reasons aren\'t living tgthr, Violence, abuse?',
    'm2a9g': 'Why did relationship end? Violent/abusive',
    'f5a4k_7': 'A4K_7. Violent/abusive',
    'm4j33a': 'Did she ever abuse prescrip drugs (valium, sleeping pills, or diet pills)?',
    'f1b10a9': 'Reasons no plan to marry, Violence, abuse?',
    'm5b30a1_10': 'B30A1_10. Domestic violence or child abuse',
    'm3j47a': 'Did he abuse prescription drugs like valium/sleeping pills?',
    'f1b10b9': 'Reasons aren\'t married now, Violence, abuse?',
    'm3a8b_7': 'Why relationship ended: violence/abuse?',
    'm4j28a': 'Did he ever abuse prescrip drugs (valium, sleeping pills, or diet pills)?',
    'm5f26b2_10': 'F26B2_10. Domestic violence or child abuse',
    'f5f26b2_10': 'F26B2_10. Domestic violence or child abuse',
    'f2a8g': 'Why did relationship end? Violent/abusive',
    'm5f28a_10': 'F28A_10. Domestic violence or child abuse',
    'm4a8b_7': 'Why relationship ended: violent/abusive?',
    'f4j28a': 'Did he ever abuse prescription drugs (valium, sleeping pills, or diet pills)?',
    'p5q8_1': 'Q8_1. CPS concerned about physical abuse',
    'p5q8_2': 'Q8_2. CPS concerned about sexual abuse',
    'f3j60a': 'Did she ever abuse prescription drugs like valium/sleeping pills?',
    'm5g23a_104': 'G23A_104. Counseling or therapy for abuse',
    'f1b4f': 'Why did romantic rel end with BM, Violence, Abuse ?',
    'm1b4f': 'Why did rom rel end with (BF), Violence, Abuse ?'
}

VIOLEN = {
    'f5f28a_10': 'F28A_10. Domestic violence or child abuse',
    'f3a8b_7': 'Why relationship ended: violence/abuse',
    'm1b9b9': 'Reasons aren\'t living tgthr, Violence, abuse ?',
    'm3d7q': 'INT CHK: DID MOTHER REPORT NO VIOLENCE?',
    'm1b10b9': 'Reasons aren\'t married now, Violence, abuse?',
    'p5m4': 'M4. Afraid to let child go outside because of violence in neighborhood',
    'f3d9q': 'INT CHK: DID FATHER REPORT NO VIOLENCE FROM MOTHER?',
    'm1b10a9': 'Reason no plan to marry, Violence, abuse?',
    'f4i0o': 'Ever been afraid to let child go outside b/c violence in your neighborhood?',
    'm4i0o': 'Ever been afraid to let child go outside b/c violence in your neighborhood?',
    'm1b9a9': 'Reasons no plan to live tgthr, Violence, abuse ?',
    'f1b9a9': 'Reasons no plan to live tgthr, Violence, abuse?',
    'm3e23s': 'INT CHK: DID MOTHER REPORT NO VIOLENCE FROM CP?',
    'm3d9q': 'INT CHK: DID MOTHER REPORT NO VIOLENCE FROM FATHER?',
    'f5b26x_10': 'B26X_10. Domestic violence or child abuse',
    'f1b9b9': 'Reasons aren\'t living tgthr, Violence, abuse?',
    'm2a9g': 'Why did relationship end? Violent/abusive',
    'f5a4k_7': 'A4K_7. Violent/abusive',
    'f1b10a9': 'Reasons no plan to marry, Violence, abuse?',
    'm5b30a1_10': 'B30A1_10. Domestic violence or child abuse',
    'f1b10b9': 'Reasons aren\'t married now, Violence, abuse?',
    'm3a8b_7': 'Why relationship ended: violence/abuse?',
    'f4a8b_7': 'Why did relationship end: violence?',
    'm5f26b2_10': 'F26B2_10. Domestic violence or child abuse',
    'f5f26b2_10': 'F26B2_10. Domestic violence or child abuse',
    'f2a8g': 'Why did relationship end? Violent/abusive',
    'f3d7q': 'INT CHK: DID FATHER REPORT NO VIOLENCE FROM MOTHER?',
    'm5f28a_10': 'F28A_10. Domestic violence or child abuse',
    'm4a8b_7': 'Why relationship ended: violent/abusive?',
    'f1b4f': 'Why did romantic rel end with BM, Violence, A buse ?',
    'm1b4f': 'Why did rom rel end with (BF), Violence, Abuse ?'
}

WELFARE = {
    'm5f14b': 'F14B. Reason the welfare office stopped or cut off your cash aid',
    'm2h9b1': 'How many months did you receive help from welfare/TANF?',
    'm4i15': 'INT CHK: WAS RESPONDENT ON WELFARE/TANF IN LAST 12 MONTHS?',
    'm5f11b': 'F11B. Number of months you been receiving welfare this time',
    'm2h9c1': 'How much money did you receive last month from welfare/TANF?',
    'm4i8b1': 'How many months did you receive help from welfare or TANF in the last 12 months?',
    'm5f8a1': 'F8A1. Received income from welfare/TANF in last 12 months',
    'm5f16': 'F16. Required to do anything in return for welfare benefits',
    'm5f14': 'F14. Reason stopped receiving welfare/TANF benefits',
    'm4i13b': 'When did you last receive welfare or TANF (year)?',
    'm5f10': 'F10. Currently receiving welfare or TANF',
    'm4i13a': 'When did you last receive welfare or TANF (month)?',
    'm4i11a': 'For how long have you been receiving welfare this time (years)?',
    'm5f13a': 'F13A. Year you last received welfare or TANF',
    'm2h16a': 'Did you apply for welfare in past 12 months?',
    'm2h16b': 'What was the result of the application for welfare?',
    'm3i8a1': 'In past year, received help from welfare or TANF?',
    'f2h8a1': 'In past 12 months have you received help from Welfare or TANF?',
    'm4i8c1': 'Approximately how much did you receive last month from welfare or TANF?',
    'm5f8b1': 'F8B1. Number of months received income from welfare/TANF in last 12 months',
    'f5f8c1': 'F8C1. Approximate amount received in the last month you received welfare/TANF',
    'm2h11a1': 'When did you last receive welfare/TANF?-(Month)',
    'm2h11a2': 'When did you last receive welfare/TANF?-(Year)',
    'm3i8c1': 'How much did you receive the last month you received welfare/TANF?',
    'f2h8b1': 'How many mons did you receive help from welfare/TANF in last 12 mons?',
    'f5b17c': 'B17C. Action taken by welfare office/court/judge to get you to pay child support',
    'f2h9d2': 'When did you last receive welfare/TANF?-(Year)',
    'f2h9d1': 'When did you last receive welfare/TANF?-(Month)',
    'm4i11b': 'For how long have you been receiving welfare this time (months)?',
    'f3i7d': 'Since child\'s first birthday, helped by welfare office?',
    'm2h10b': 'Is respondent currently receiving welfare or TANF?',
    'm2h10a': 'Int Chk: Did mother receive welfare/TANF in last 12 months?',
    'f5f11a': 'F11A. Number of years you have been receiving welfare this time',
    'f5f11b': 'F11B. Number of months you been receiving welfare this time',
    'f2h8c1': 'How much help did you receive from welfare in the last month?',
    'f1f11a': 'How many yrs can a mother receive welfare before she is required to work?',
    'f5f8a1': 'F8A1. Received income from welfare/TANF in last 12 months',
    'f4i23p1': 'Agree/disagree: Welfare makes people work less than would if there wasn\'t welfar',
    'f4i23p3': 'Agree/disagree: Welfare encourages young women to have babies before marriage',
    'f4i23p2': 'Agree/disagree: Welfare helps people get on feet when facing difficult situation',
    'f4i23p5': 'Agree/disagree: Welfare helps to prevent hunger and starvation',
    'f4i23p6': 'Agree/disagree: Welfare discourages women who get pregnant from marrying father',
    'm3i16': 'Were you required to do anything in return for welfare benefits?',
    'f4i23q2': 'Agree/disagree: The rules of welfare program take away personal freedom',
    'f4i23q1': 'Agree/disagree: The application process to apply for welfare is humiliating',
    'm5f8c1': 'F8C1. Approximate amount received in the last month you received welfare/TANF',
    'f5f13a': 'F13A. Year you last received welfare or TANF',
    'm5f18c': 'F18C. Reason you did not apply for welfare',
    'm3i12': 'Have you ever received welfare or TANF?',
    'm4i23q2': 'Agree/disagree: The rules of welfare program take away personal freedom',
    'f5f14b': 'F14B. Reason the welfare office stopped or cut off your cash aid',
    'f3i10': 'Are you currently receiving welfare or TANF?',
    'm5f7b': 'F7B. Received help from a welfare office or welfare job placement in past 12 mon',
    'm4i23p3': 'Agree/disagree: Welfare encourages young women to have babies before marriage',
    'f4i15': 'INT CHK: WAS RESPONDENT ON WELFARE/TANF IN LAST 12 MONTHS?',
    'f4i16': 'Were you required to do anything in return for welfare benefits?',
    'f4i18': 'Ever time in past 12 months that you thought you might be eligible for welfare?',
    'n5a16_4': 'A16_4. NPCG receives payments from TANF/welfare',
    'f1f10b': 'How many months in total can a mother receive welfare?',
    'f1f10a': 'How many years in total can a mother receive welfare?',
    'f1k2a': 'How much money did you receive from Public assis./Welfare etc.?',
    'm4i14b': 'Why did the welfare office stop or cut off your aid?',
    'f1f11b': 'How many mos can a mother receive welfare before she is required to work?',
    'm5f18b': 'F18B. Result of welfare application',
    'f3i18': 'In the past year, did you think that you were eligible for welfare at any time?',
    'f3i18a': 'Did you apply for welfare in past year?',
    'f3i12': 'Have you ever received welfare or TANF?',
    'f3i15': 'WAS R ON WELFARE OR TANF IN PAST 12 MONTHS?',
    'f3i16': 'Were you required to do anything in return for welfare benefits?',
    'm4i9': 'INT CHK: DID MOTHER RECEIVE WELFARE/TANF IN LAST 12 MONTHS?',
    'm3i8b1': 'How many months did you receive welfare/TANF in the past year?',
    'f4i23p4': 'Agree/disagree: Welfare helps keep marriages together in times of financial prob',
    'f4c21c': 'Action taken by welfare office/court judge to get you to pay support?',
    'f1f9': 'Can M receive welfare if she is not married and lives with BF?',
    'f2h9c': 'Have you ever received welfare/TANF?',
    'f4i9': 'INT CHK: DID FATHER RECEIVE WELFARE OR TANF IN LAST 12 MONTHS?',
    'm4i7f': 'In past 12 months, received help from welfare office or welfare job placement?',
    'm4i18a': 'Did you apply for welfare in the past 12 months?',
    'm5f18a': 'F18A. You applied for welfare in the past 12 months',
    'm2h11': 'Have you ever received welfare/TANF?',
    'm2h13': 'Int Chk: Was respondent on welfare/TANF in the past 12 month?',
    'm2h14': 'Were you required to do anything in return for welfare benefits?',
    'm2h16': 'Was there time in last 12 mons you thought you might be eligible for welfare?',
    'm3i7g': 'Since child\'s first birthday: helped by welfare/job placement office?',
    'm2h10c2': 'For how long have you been receiving welfare/TANF?-(In months)',
    'm3c21c': 'Welfare office/court/judge tried to get father to pay child support owed?',
    'm5f11a': 'F11A. Number of years you have been receiving welfare this time',
    'f4i7f': 'In past year, received help from welfare office or welfare job placement?',
    'm2h10c1': 'For how long have you been receiving welfare/TANF?-(In years)',
    'f3i9': 'INT CHK: DID R RECEIVE WELFARE OR TANF IN LAST 12 MONTHS?',
    'f2h9a': 'Are you currently receiving welfare or TANF support?',
    'm4i17': 'Welfare ben reduced/cut in past 12 months b/c did not fulfill these requirements',
    'f2h14b': 'What happened with the application for welfare?',
    'f2h14a': 'Did you apply for welfare in past 12 months?',
    'm5f12': 'F12. Received welfare or TANF at any time over the last four years',
    'm5f11': 'F11. Length of time you have been receiving welfare this time',
    'f1f8': 'Can M receive welfare if she is married and living with her husband?',
    'm2h9a1': 'In past 12 months have you received help from Welfare or TANF?',
    'f5f8b1': 'F8B1. Number of months received income from welfare/TANF in last 12 months',
    'm5f18': 'F18. Ever a time in past 12 months you thought you might be eligible for welfare',
    'm4i8a1': 'In the past 12 months, have you received income from welfare or TANF?',
    'm5f17': 'F17. Welfare benefits cut in past 12 months because you did not fulfill requirem',
    'm5f13': 'F13. Month you last received welfare or TANF',
    'm4i23p2': 'Agree/disagree: Welfare helps people get on feet when facing difficult situation',
    'm4i23p4': 'Agree/disagree: Welfare helps keep marriages together in times of financial prob',
    'fx2h14a': 'TCO-Did you ever apply for welfare?',
    'f5f18': 'F18. Ever a time in past 12 months you thought you might be eligible for welfare',
    'f5f14': 'F14. Your decision to stop receiving welfare/TANF or welfare department stopped',
    'f5f17': 'F17. Welfare reduced/cut in past 12 months because did not fulfill requirements',
    'f5f16': 'F16. Required to do anything for welfare benefits',
    'f5f11': 'F11. Length of time you have been receiving welfare this time',
    'f5f12': 'F12. Received welfare or TANF at any time over the last four years',
    'f2h9': 'Int Chk: Did father receive welfare or TANF in the last 12 months?',
    'f3i11b': 'For how long have you been receiving welfare? (months)',
    'f3i11a': 'For how long have you been receiving welfare? (years)',
    'm4i23q1': 'Agree/disagree: The application process to apply for welfare is humiliating',
    'm1j2b': 'In 12 mo, about how much money did you receive from pub. assis/welfare?',
    'm4i23p1': 'Agree/disagree: Welfare makes people work less than would if there wasn\'t welfar',
    'f4i11a': 'For how long have you been receiving welfare this time? (years)',
    'f4i11b': 'For how long have you been receiving welfare this time? (months)',
    'm3i18a': 'Did you apply for welfare in past year?',
    'm1f11a': 'How long can a mother receive welfare before being required to work?-years',
    'm1f11b': 'How long can a mother receive welfare before being required to work?-months',
    'f3i13a': 'When did you last receive welfare or TANF? (month)',
    'f3i13b': 'When did you last receive welfare or TANF? (year)',
    'f2h14': 'Was there point/last 12 mths you thought you might be eligible for welfare?',
    'f2h11': 'Int Chk: Was respondent on welfare or TANF in the last 12 months?',
    'f2h9b1': 'For how long have you been receiving welfare/TANF?-(Years)',
    'f4i13b': 'When did you last receive welfare or TANF? (year)',
    'f4i13a': 'When did you last receive welfare or TANF? (month)',
    'f5f10': 'F10. Currently receiving welfare or TANF',
    'f5f13': 'F13. Month you last received welfare or TANF',
    'm1f8': 'Can mother receive welfare if she is married and living with husband?',
    'm1f9': 'Can mother receive welfare if she is not married and lives with BF?',
    'f4i14b': 'Why did the welfare office stop or cut off your aid?',
    'mx2h14a': 'TCO-Did you ever apply for welfare?',
    'f3c21c': 'Has welfare office/court/judge tried to get you to pay child support you owe?',
    'm1f10b': 'How long in total can a mother receive welfare (months)?',
    'm1f10a': 'How long in total can a mother receive welfare (years)?',
    'm3c38c': 'Any action taken by welfare office/court/judge to get him to pay?',
    'm3i9': 'INT CHK: DID MOTHER RECEIVE TANF OR WELFARE IN PAST YEAR?',
    'm3i18': 'In past year, did you think you were eligible for welfare at any time?',
    'm3i15': 'Was respondent on welfare/TANF in last year?',
    'm3i10': 'Are you currently receiving welfare or TANF?',
    'f5f7b': 'F7B. In the past twelve months, have you received help from a welfare office',
    'm4i16': 'Were you required to do anything in return for your welfare benefits?',
    'm4i14': 'When stopped receiving welfare/TANF, your decision or welfare dept\'s decision?',
    'm4i12': 'Have you ever received welfare or TANF?',
    'm4i10': 'Are you currently receiving welfare or TANF?',
    'm4i18': 'Ever time in past 12 months that you thought you might be eligible for welfare?',
    'f4i8c1': 'Approximately how much did you receive last month from welfare or TANF?',
    'm4c21c': 'Any action by welfare office/court/judge to get father pay child supp owes?',
    'f5f18b': 'F18B. Result of welfare application',
    'f5f18c': 'F18C. Reason you did not apply for welfare',
    'f5f18a': 'F18A. You applied for welfare in the past 12 months',
    'f3i8b1': 'How many months out of past 12 did you receive welfare or TANF?',
    'f4i8b1': 'How many months did you receive help from welfare or TANF in the last 12 months?',
    'f4i14': 'When stopped receiving welfare/TANF, your decision or welfare dept\'s decision?',
    'f4i17': 'Welfare benefits reduced/cut in past year b/c did not fulfill these requirements',
    'f4i10': 'Are you currently receiving welfare or TANF?',
    'f4i12': 'Have you ever received welfare or TANF?',
    'm1j1b': 'In last yr did you have income from public assistance/welfare/food stamps?',
    'm2c16': 'Does father owe child support/birthing costs to you/welfare department?',
    'm3i13a': 'When did you last receive welfare or TANF? (month)',
    'm3i13b': 'When did you last receive welfare or TANF? (year)',
    'f4i18c': 'Why didn\'t you apply for welfare?',
    'f4i18a': 'Did you apply for welfare in the past 12 months?',
    'f3i8c1': 'Approximately how much did you receive the last month you had welfare? ($)',
    'f2h7a': 'Since child\'s birth, have you received help from-employment/welfare agency?',
    'f2h7c': 'What other kinds of help have you received(Except TANF or welfare)?- Other, spec',
    'f4i8a1': 'In the past 12 months, have you received income from welfare or TANF?',
    'f3c21': 'Do you owe anything to the welfare dept or mother for unpaid child support?',
    'f3c38b': 'Has any action been taken by welfare office/court/judge to get you to pay?',
    'm4i18c': 'Why didn\'t you apply for welfare?',
    'f2h9b2': 'For how long have you been receiving welfare/TANF?-(month)',
    'm3i11b': 'For how long have you been receiving welfare? (months)',
    'm3i11a': 'For how long have you been receiving welfare? (years)',
    'f3i8a1': 'In past 12 months, have you received help from welfare or TANF?',
    'm4i23p6': 'Agree/disagree: Welfare discourages women who get pregnant from marrying father',
    'm4i23p5': 'Agree/disagree: Welfare helps to prevent hunger and starvation'
}


def main():

    X = pd.read_pickle('data/private/X_cleaned.p')
    print('X shape: (%s, %s)' % X.shape)

    FEATURES = {}
    FEATURES.update(EVICT)
    FEATURES.update(RENT)
    FEATURES.update(MORTGAGE)
    FEATURES.update(MONEY)
    FEATURES.update(JOB)
    FEATURES.update(EMPLOY)
    FEATURES.update(DISAB)
    FEATURES.update(WELFARE)
    FEATURES.update(PREGNAN)
    FEATURES.update(BOYFRIEND)
    FEATURES.update(ABUS)
    FEATURES.update(VIOLEN)

    X = X.loc[:, FEATURES.keys()]

    print('Number of features: %s' % X.shape[1])
    X.to_pickle('data/private/X_eviction_handcrafted.p')

if __name__ == '__main__':
    main()
